---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[gpac::default]
    attributes:
      gpac:
        dependencies: []
